trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables: 
  solution: P1_ASP_WebApp/P1_ASP_WebApp.sln

stages: 
- stage: build
  jobs:
  - job: build
    
    steps:

    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(solution)

    - script: dotnet test --configuration Release
      displayName: dotnet test
      workingDirectory: $(solution)