trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: windows-latest

variables: 
  solution: P1_ASP_WebApp

stages: 
- stage: build
  jobs:
  - job: build
    
    steps:
    - task: UseDotNet@2
      displayName: dotnet-sdk-5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: UseDotNet@2
      displayName: dotnet-runtime-r.1
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: SonarCloudPrepare@1
      displayName: sonar prepare
      inputs:
        SonarCloud: ''
        organization: '210726-wvu-net-ext'
        scannerMode: 'MSBuild'
        projectKey: ''
        extraProperties: |
          sonar.exclusions=**/lib/**/*
          sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/*/coverage.opencover.xml
      

    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(solution)

    - script: dotnet test --configuration Release
        -- collect:Path"XPlat Code Coverage"
        --results-directory $(Agent.TempDirectory) 
        DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      displayName: dotnet test
      workingDirectory: $(solution)
      
    - task: SonarCloudAnalyze@1
      displayName: sonar analyze

    - task: SonarCloudPublish@1
      displayName: sonar publish gate
      inputs:
        pollingTimeoutSec: '300'
    
    - script: dotnet publish
        --configuration Release
        --output $(Build.StagingDirectory)
      displayName: dotnet publish
      workingDirectory: $(solution)

    - publish: $(Build.StagingDirectory)
      displayName: publish app artifact
      artifact: app
