trigger:
  branches:
    include:
      - main
  paths:
    include:
      - P1-Christopher-Mesidor
      - P1-Christopher-Mesidor/azure-pipelines.yml

pr: none


stages:
- stage: build
  jobs:
    - job: build

      pool:
        vmImage: ubuntu-latest

      steps:
      - script: ls
        displayName: ls
