trigger:
  branches:
    include:
    - main
  paths:
    include:
    - P1-Christopher-Mesidor
    - P1-Christopher-Mesidor/azure-pipelines.yml

pr:
  branches:
    include:
    - main
  paths:
    include:
    - P1-Christopher-Mesidor
    - P1-Christopher-Mesidor/azure-pipelines.yml


stages:
- stage: build
  jobs:
  - job: build

    pool:
      vmImage: ubuntu-latest

      steps:
      - script: dotnet build --configuration Release
        displayName: dotnet build (script)
        workingDirectory: $(P1-Christopher-Mesidor)

      - script: dotnet test --configuration Release
        displayName: dotnet test ()task
        workingDirectory: $(P1-Christopher-Mesidor)
