trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
- task: NuGetCommand@2
  inputs:
    restoreSolution: $(P1-Christopher-Mesidor/P1_ASP_WebApp/P1_ASP_WebApp.sln)

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(Any CPU)'
    configuration: '$(Release)'

- task: VSTest@2
  inputs:
    platform: '$(Any CPU)'
    configuration: '$(Release)'